### PR TITLE
Feat/weak auras support

### LINKED ISSUE #401: Support updating weak auras from wago.io
Many players nowadays have more weak auras than actual add-ons. Keeping them updated requires manual intervention or the usage of yet another add-on manager ( https://weakauras.wtf ).

It would be nice if this functionality could be integrated into ajour. [Cursebreaker](https://github.com/AcidWeb/CurseBreaker) does support updating weak auras.

### PR DESCRIPTION
**Pull request by tarkah**
Resolves #401 

## Proposed Changes
  - Update installed weak auras for selected flavor / account

## Checklist

- [x] Tested on Windows
- [x] Tested on MacOS
- [ ] Tested on Linux
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users

### CODE REVIEW

**Comment by tarkah** [comment]
Have the basic lua parsing done and api call to get info about each aura. I'm testing the general flow in the `bin` but will move everything over to the lib once I have my head around things.

**Comment by tarkah** [comment]
You can test it with `cargo run -- path/to/<flavor>/WTF/Account/<MyAccount>/SavedVariables/WeakAuras.lua`

**Comment by casperstorm** [comment]
Amazing mate, damn its gonna be a nice addition.

**Comment by casperstorm** [comment]
You can now quite easily hook up some logic to the GUI, @tarkah.
I'll keep working on it once we get a little further with the data modelling.

Screenshot 2020-12-16 at 13 40 59

**Comment by casperstorm** [comment]
Gonna do some polishing on the GUI as well today.
One thing I found tho, @tarkah - when running it on my PC I get:

```sh
08:47:01.390 [ajour][ERROR] Failed to parse Weak Auras
08:47:01.390 [ajour][ERROR] caused by: error converting Lua nil to String (expected string or number)
```

[WeakAuras.zip](https://github.com/casperstorm/ajour/files/5707721/WeakAuras.zip)

**Comment by tarkah** [comment]
Ahh, I just need to convert one of the fields to an option then since it doesn't exist on every item

**Comment by casperstorm** [comment]
> Ahh, I just need to convert one of the fields to an option then since it doesn't exist on every item

Nice. I am just posting everything I find. :)
Another thing I saw, which could be a QOL: if you have multiple accounts, we should consider saving the selected one so you don't have to select it every time.

**Comment by casperstorm** [comment]
Dunno why CHANGELOG is failing our markdownlint, it should be good - you see anything @tarkah?

**Comment by casperstorm** [comment]
All good here, except the linter action is complaining? Hm.
When thats fixed, i say we merge.

**Pull request merged**
