### PR TITLE
Categories per source

### LINKED ISSUE #360: Do not allow empty categories
Problem :

Categories are tied to an API (curse, wowi), but the APIs do not always share the same name.

So if you select API1 and a category from API2, the addon list ends empty, without much feedback on why.

Solution :

1) Make it so the combo only shows categories from the selected API

2) Rename categories so they are the same in both API

### PR DESCRIPTION
**Pull request by Mazwak**
Resolves #360

## Proposed Changes
  - Only list categories relevant to the source selected

## Checklist

- [x] Tested on Windows
- [x] Tested on MacOS
- [ ] Tested on Linux
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users

### CODE REVIEW

**Comment by Mazwak** [comment]
It works, but there is a function to extract, as I copy/paste from calagog load into source changed

**Comment by Mazwak** [comment]
This should be better now.

Lists are only processed once.
There is almost no copy paste.

**Comment by casperstorm** [comment]
@tarkah any feedback? LGTM.

**Comment by tarkah** [comment]
Looks good here as well. Great job @Mazwak!

**Pull request merged**
