### PR TITLE
Add french translation

### PR DESCRIPTION
**Pull request by Nelfym**
Not sure if fr_FR.json must be declared in another file.

Resolves #

## Proposed Changes
  -

## Checklist

- [ ] Tested on Windows
- [ ] Tested on MacOS
- [ ] Tested on Linux
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users

### CODE REVIEW

**Comment by tarkah** [comment]
@Nelfym this is so great you have already picked up on our new feature and added this! I think @casperstorm is getting really close to finalizing the localization PR. Once done, you can make sure your fr_FR.json file is fully up to date, and we can take care of the rest.

**Comment by Nelfym** [comment]
@tarkah Thanks. I've just updated my PR with latest changes, i'll keep an eye on futures changes.

**Comment by casperstorm** [comment]
@Nelfym all keys should be there now ready to be translated. Thank you so much for this 🙏🏻.

**Comment by Nelfym** [comment]
Just updated my PR. I'm ready, if no change on en_US feel free to merge :).

**Comment by casperstorm** [comment]
Thank you @Nelfym.

**Pull request merged**
