### PR TITLE
add optional columns & reordering

### PR DESCRIPTION
**Pull request by tarkah**
Resolves https://github.com/casperstorm/ajour/projects/2#card-45790708

## Proposed Changes
  - Add section to settings to allow toggling visibility of columns & reordering columns
  - Add optional columns (unchecked by default): Game Version, Author, Last update date, Channel
  - Persist changes to config file

## Checklist

- [ ] Tested on all platforms changed
- [x] `cargo fmt` has been run on this branch
- [x] `cargo clippy` has been run on this branch
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users

### CODE REVIEW

**Comment by tarkah** [comment]
I've got a core amount of the work done and tested so far w/ two optional columns "Author" & "Channel". Still need to add reordering buttons and config persistence.

This PR is currently a mess. Once I have a fully working prototype, I am going to refactor a good portion of this.

**Comment by casperstorm** [comment]
Looks good @tarkah – i can't wait to get this into the app. More customization for the win!

**Comment by tarkah** [comment]
@casperstorm I think this is a fairly good spot for you to test

**Comment by casperstorm** [comment]
This works nicely. Awesome job.

**Comment by tarkah** [comment]
Great! I'm going to make the checkbox for the Addon column appear "disabled" since you can't really uncheck it, then I think we are good to go.

**Comment by tarkah** [comment]
I've rebased against #154

**Pull request merged**
