### PR TITLE
fix: linux resizable

### LINKED ISSUE #427: Application no resizable on wayland since 0.5.4
**Describe the bug**
Application window no resizable on wayland since 0.5.4

**To Reproduce**
Launch app on wayland, try to resize, you cannot

It worked on 0.5.3

**Expected behavior**
We should ensure resizing works

**Screenshots**
Capture d’écran du 2020-12-10 16-04-15

Also the maximize doesn't work neither

**Software involved**
Please complete the following information:
 - OS: Archlinux
 - Ajour version: 0.5.4

**Additional context**

**Log Output**
I take a look but there is no error or warning, only valid info

### PR DESCRIPTION
**Pull request by casperstorm**
Resolves #427 

## Proposed Changes
  - Disabled minimum window size on Linux because it causes the window to become non-resizable.

## Checklist

- [ ] Tested on Windows
- [X] Tested on MacOS
- [x] Tested on Linux
- [X] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users

### CODE REVIEW

**Comment by casperstorm** [comment]
@tarkah @nerzhul Can you guys this this branch to see if it fixes the issue?

**Comment by tarkah** [comment]
I'm not using Wayland so I can't test, but the change looks correct.

**Comment by tarkah** [comment]
@lub can you confirm this branches resolves the resize issue?

**Comment by casperstorm** [comment]
Confirmed to work: https://github.com/casperstorm/ajour/issues/444#issuecomment-749377010

**Pull request merged**
