### PR TITLE
Chore/bump dependencies

### LINKED ISSUE #252: Wayland startup issue
**Describe the bug**
Failed to startup app under gnome + wayland

```[wayland-client error] Attempted to dispatch unknown opcode 0 for wl_shm, aborting.
zsh: abort (core dumped)  ajour
```

**To Reproduce**
Just launch app on gnome + wayland

**Expected behavior**
It should startup

**Screenshots**
See the desription

**Software involved**
Please complete the following information:
 - OS: Archlinux
 - Ajour version: 0.4.1

**Additional context**
N/A

**Log Output**
See description

### PR DESCRIPTION
**Pull request by tarkah**
Resolves #252

### CODE REVIEW

**Comment by nerzhul** [comment]
testing it

**Comment by nerzhul** [comment]
Capture d’écran de 2020-10-24 18-20-42

Works very very fine, nice job

**Comment by tarkah** [comment]
Great! Thanks for testing

**Review by casperstorm — APPROVED** [review]

**Comment by casperstorm** [comment]
Approved, you can merge when you want.

**Pull request merged**
