### PR TITLE
feat: tukui addons

### PR DESCRIPTION
**Pull request by petergp**
## Proposed Changes
  - Uses `catalog` feed to show both curse and tukui addons in catalog
  - Append `X-Tukui-ProjectID` to `toc` file for Tukui addons with that field missing (only support for archives containing just 1 addon. Some archives from tukui are a collection of addons)

Most tukui addons work, but some doenst because the zip archive contains multiple addons and the main one doenst have the `X-Tukui-ProjectID` key set. I haven't found a reliable way where I can detect which of the addons in an archive with multiple that I should add the id to. My suggestion is that we blocklist addons that we know is not working in the catalog.

## Checklist

- [ ] Tested on all platforms changed
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users

### CODE REVIEW

**Comment by casperstorm** [comment]
We should get this back-merged so we can merge it together with #315.

**Comment by tarkah** [comment]
@casperstorm I've enabled the Tukui catalog already in #315. I assume we don't want to modify `.toc` entries from this PR as we now have the cache?

**Comment by casperstorm** [comment]
> @casperstorm I've enabled the Tukui catalog already in #315. I assume we don't want to modify `.toc` entries from this PR as we now have the cache? 

True. Forgot this was more than just enabling catalog.

**Comment by casperstorm** [comment]
Closing for now in favor for the new caching system.

**Pull request closed without merging**
