### PR TITLE
add appimage release

### LINKED ISSUE #137: Provide Ubuntu/Linux port
**Is your feature request related to a problem? Please describe.**
I am playing WoW with lutris/wine which works perfect. 
I tried running your .exe with wine but it crashed

**Describe the solution you'd like**
Could you provide a port of your app for Ubuntu/Linux?

**Describe alternatives you've considered**
Make it work with wine but I would clearly prefer a real port. Maybe you could provide a snap or deb installation file

### PR DESCRIPTION
**Pull request by tarkah**
Resolves #137 #162

## Proposed Changes
  - release AppImage that can be run on any linux distro

## Checklist

- [x] Tested on all platforms changed
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users

### CODE REVIEW

**Comment by tarkah** [comment]
@casperstorm message me when you're online, I created an AppImage for `0.3.5` that we can publish to that release. I'm not too familiar with Makefile format, but I added a line in there to create the AppImage. I can provide this for future releases until we get it integrated into our github actions. I'm going to close out #179 for now, since I don't think it's necessary anymore.

I've tested this on a fresh Ubuntu 20.04 live image, and a ~1year old live image of Solus that I had laying around. Both worked out of the box perfectly!

**Comment by casperstorm** [comment]
@tarkah I think this is looking good.
Only question is if we should rename `app` in make to something else so its releated to macos. `app` and `appimage` is a bit confusion now. Other than that this is approved.

**Comment by tarkah** [comment]
`.AppImage` is the official extension.. but maybe we can make it like `Ajour-Linux.AppImage`?

**Comment by casperstorm** [comment]
> `.AppImage` is the official extension.. but maybe we can make it like `Ajour-Linux.AppImage`?

Looking at it again i think its fine tbh.  
`app` does generate a `.app`
`appimage` does generate a `.appimage`
It was just - you need to know to know right? But I think its fine, it will be bound to CI soon so its out of human touch.

https://github.com/casperstorm/ajour/blob/a9ffcb0f582d9552a8886e65cad3ceb9b10d591e/Makefile#L62

https://github.com/casperstorm/ajour/blob/a9ffcb0f582d9552a8886e65cad3ceb9b10d591e/Makefile#L39

But looking at it again it's

**Pull request merged**
