### PR TITLE
refactor addon and addon parsing

### LINKED ISSUE #233: Fallback strategy to improve addon recognition
**Is your feature request related to a problem? Please describe.**
Currently Ajour does not handle local addons that do not return a match from either CurseForge fingerprint endpoint or failing that, using the X-Tukui-ProjectID. This leaves us unable to show non-tukui addons that have been modified locally, or that have received updates not yet posted on CurseForge. 

**Describe the solution you'd like**
 - If fingerprint endpoint doesn't return match: Use Curse ID from toc. Leave local version blank and give user `Repair` button to reinstall addon with latest from source. 
 - For remaining unrecognized folders, list them 1:1 and advice user to find and reinstall them through Catalog.
 - When installing addons through Catalog, make note of folder names contained in archive and correlate that with id from source. Use that correlation going forward if fingerprinting fails to return a match.

### PR DESCRIPTION
**Pull request by tarkah**
Resolves #233 

## Checklist

- [x] Tested on all platforms changed
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users

### CODE REVIEW

**Comment by tarkah** [comment]
Ok... this is going to be a pretty major PR. I decided to tackle refactoring `addon.rs` and `parse.rs`. I haven't touched `ajour` / gui yet, but I am able to test these changes currently with `cargo run --bin parse_addon_directory -- <path>`. I need to install some tukui addons to fully test.

I think it's really important to make the distinction between the following:

- `AddonFolder`... the actual folders and the `.toc` metadata we are able to parse from them. Nothing else. So basically just what lives on the filesystem.
- `RepositoryMetadata` - The information we can get about an addon from the repository
- `Addon` - this is kind of an abstract thing that doesn't actually _live_ on somoeones system. It is the glue that combines the `RepositoryMetadata` and bundles `AddonFolders` together to make an `"Addon"`. And where we store any other state / user defined preferences for the addon.

From this, I feel I am able to reason about everything a lot better. We parse all of the folders into `Vec<AddonFolder>`. Then we fingerprint all folders and extract any relevant repo identifies from them. From here, we can start querying the different APIs and generating our actual `Addon` structs on the relevant info.

As far as getting information from the `Addon`, I am planning on setting up `getter` methods that will work as follows. If we have `RepositoryMetadata` for an addon, it will try to get the value from there. If not, it will try to get that same metadata from the primary `AddonFolder` designated for the addon.  The `primary_folder_id` is intended to work just like the old `id`, as in it can be a unique identifier, but it also determines which `AddonFolder` we will try to query as a backup to `RepositoryMetadata` for values. When building an `Addon` for Curse with `RepositoryMetadata` and the slice of `AddonFolder`that matches the curse file module names, I just take the first folder name alphabetically (that appears to match how it's currently done). For Tukui, we just use the `AddonFolder` which had the tukui id.

Hopefully this all makes sense as you read through the diff and you think it's the right approach!

Note that I haven't actually tackled the fallback strategy yet, I'll add that next. Just wanted to get this major refactor out of the way first.

**Comment by casperstorm** [comment]
While working on #107 I noticed something which we might wanted to handle now you are refactoring.
Consider the following:

```
15:37:57.419 [ajour_core::parse][DEBUG] retail - 1 addons with tukui id
15:37:57.532 [ajour_core::parse][DEBUG] retail - 0 addons applied with tukui id package metadata
15:37:57.532 [ajour_core::parse][DEBUG] retail - 1 unique fingerprints to check against curse api
15:37:57.705 [ajour_core::parse][DEBUG] retail - 0 exact fingerprint matches against curse api
15:37:57.705 [ajour_core::parse][DEBUG] retail - 0 addons applied with fingerprint metadata
```

In this case we see we have 1 addon with a tukui, but we didn't find any in the tukui api, and we didn't find any in the curse api.
So how could we debug this better? Right now we can't actually see that the problem is because the tukui api is down.
Just a thought for improvement.

**Comment by tarkah** [comment]
Yeah that relates perfectly to the API issues going on. Without any data from the API, we either don't show the addon and show an error message, show the addon as "unknown" and 1:1 to AddonFolder, OR implement some cache we can fallback on and an offline status.

**Comment by tarkah** [comment]
@casperstorm I feel this is in a pretty good spot. 

A big gap I caught that was introduced by this PR that I just fixed is around installing an Addon from the catalog. If a user installs an addon from the catalog, it was getting stuck on fingerprinting since the `AddonFolder`s of the addon weren't set. I've added logic to parse the `AddonFolder`s during the unzipping process and return them. Then if that download / unpack process was triggered due to the Catalog install, I'll use those addon folders to properly set the `folders` and `primary_folder_id` of the addon after unpacking finishes and before fingerprinting starts. This also fixes a gap if a user wants to delete the addon through Ajour after installing it from the catalog, it will now delete the folders since they're set on the addon.

It's worth noting that because of the spotty-ness of the fingerprinting API currently, certain addons (Details! specifically), are not getting returned. So when you `Refresh` a bunch of times, that addon goes from good to `Repair` and back and forth. That will obviously be confusing for people, but I guess less confusing than before where it just didn't show up :P Until we implement a local cache to fallback on, this will be a problem when the APIs suck.

I also rebased to Development and got the awesome changelog stuff working here :)

**Comment by casperstorm** [comment]
Impressive, @tarkah. This is a giant leap forward.
I've tested, and for once it actually is kinda funny that the API is wonky so I easily cant test different states.
It's awesome. I tested it quite a lot and didn't find any problems. Went through code and looks clean as well. Much better than what we came from.

I just updated two with two commits:
- Removed the old dependency linking: https://github.com/casperstorm/ajour/pull/235/commits/b8f9f91520b673ce8784a5b90e02c926887a472c
- Renamed the `download_directory_for_flavor`: https://github.com/casperstorm/ajour/pull/235/commits/a7dde8fb5ad54acc1a7a6699e08209d57cbc58a4

I'll merge this to development and then we can do some testing on that branch.

Good job, man. Really good job.

**Pull request merged**
