### PR TITLE
add snap package

### PR DESCRIPTION
**Pull request by tarkah**
partially satisfies #137 

## Proposed Changes
  - Provide a `.snap` that linux users can install

## Checklist

- [ ] Tested on all platforms changed
- [ ] `cargo fmt` has been run on this branch
- [ ] `cargo clippy` has been run on this branch
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users

### CODE REVIEW

**Comment by tarkah** [comment]
So I've got this _working_, however there is one critical issue that's holding this up. The `Select Directory` buttons don't work / don't open a file explorer. I have not found an elegant solution to resolve this in the snap ecosystem yet. Figured I'd open this in the meantime, maybe someone else has experience with how to address this?

**Comment by tarkah** [comment]
Our current dependency for opening files basically uses `which` to figure out if `zenity` or `Kdialog` is on the system, then uses those. Because the snap is confined, this doesn't work.

**Comment by LEGOL2** [comment]
I've tried to create appimage file on linux. It's a standalone executable, that does not require any deps or installation, just run it. It works fine, but it needs some testing. Also I need to dig deeper into into it to make automated generation (as for now I did it by had). Check this [website](https://appimage.org/) for more info.

I've read that we can automate it with some travis CI jobs, but I have to research it.

**Comment by tarkah** [comment]
@LEGOL2 as mentioned in discord, I think that's the way to go. Way simpler than Snap and anyone can just run it. And we don't need to work around confinement issues.

Can you outline the steps you took to successfully create the image? I followed their guides and used the `linuxdeploy` tool, but I must have done something wrong because I couldn't get it working. I'd love to integrate that into our github actions.

**Comment by LEGOL2** [comment]
1. Compile ajour
2. Get `linuxdeploy` and call `./linuxdeploy-x86_64.AppImage --appdir AppDir`
3. It creates AppDir catalog
4.
```
.
└── usr
    ├── bin
    │   └── ajour
    ├── lib
    └── share
        ├── applications
        │   └── ajour.desktop
        └── icons
            └── hicolor
                ├── 128x128
                │   └── apps
                ├── 16x16
                │   └── apps
                ├── 256x256
                │   └── apps
                │       └── ajour.png
                ├── 32x32
                │   └── apps
                ├── 64x64
                │   └── apps
                └── scalable
                    └── apps
```
`ajour.desktop` should look like this:
```
[Desktop Entry]
Type=Application
Terminal=false
Exec=ajour
Name=Ajour
Icon=ajour
Categories=Game;
```
5. Call `./linuxdeploy-x86_64.AppImage --appdir AppDir --output appimage`

**Comment by tarkah** [comment]
Got it working, thanks for those steps!

**Comment by casperstorm** [comment]
Releated to flatpak: https://www.flatkill.org/2020/.

**Comment by tarkah** [comment]
Interesting, thanks for the link! @casperstorm, it seems like we will 100% have AppImage for releases. Do you still want to try supporting snap if possible, and then trying Flatpak as well? I need to research more, but maybe using classic confinement for the snap package solves the issue I'm running into.

**Comment by tarkah** [comment]
Closing in favor of releasing as AppImage, which is completed

**Pull request closed without merging**
