### PR TITLE
fix: localization additions

### PR DESCRIPTION
**Pull request by casperstorm**
This will fix: 
* The missing translations: "Updates Available", "Updates Queued".
* Add russian language
* Add swedish language

## Checklist

- [ ] Tested on Windows
- [ ] Tested on MacOS
- [ ] Tested on Linux
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users

### CODE REVIEW

**Comment by casperstorm** [comment]
@tarkah if you have time, and an idea - could you help me move this so we can localize it?

https://github.com/casperstorm/ajour/blob/129e349f9e3208a0e99d46358fed901338db83d4/crates/weak_auras/src/lib.rs#L251-L261

keys are:
`weakaura-update-available` and `weakaura-update-queued`.

**Comment by casperstorm** [comment]
@mlablah and @Nelfym could you help with translating the following two sentences:

  "weakaura-update-available": "Update Available",
  "weakaura-update-queued": "Update Queued"

Replying to this PR would be fine, if possible. then I can commit it. I must have missed these two earlier. They are using in `My WeakAuras`.

**Comment by Nelfym** [comment]
Hi,
```
"weakaura-update-available": "Mise à jour disponible",
"weakaura-update-queued": "Mise à jour en attente"
```

**Comment by tarkah** [comment]
I'll get this updated today

**Pull request merged**
