### PR TITLE
split ajour into bin & lib

### PR DESCRIPTION
**Pull request by tarkah**
split out ajour into a lib so we can benchmark / profile functions easier without the gui

### CODE REVIEW

**Comment by tarkah** [comment]
as discussed in #128, this is the start of moving ajour to a lib. Anything we want to reference we can throw in that `exports` module. Check out the bin `parse_addon_directory` I added. Now that I have this, I'm going to look at running the profiling for that specific function.

**Comment by tarkah** [comment]
So I think its best if we actually take all the non-gui stuff and push it into its own crate / own dependencies. Right now all the `bins` I'm creating, you still have to compile Iced which is super annoying. If we just leave the `gui` in the main ajour crate, then split everything else out to an `ajour-core` crate, we should have better compilation times when not touching the frontend at all. What do you think?

**Comment by tarkah** [comment]
Well... here's what that would look like :P I split out everything except for the `gui` module into a `ajour-core` crate. Since we store `button::State` in the Addon, I added a feature flag `gui` on the core crate, and made those fields / the `iced_native` dependency  conditional on that feature flag. Now we can use `ajour-core` in other bins without any dependency on iced / other gui libs.

I realize this is a HUGE structural change, so I completely understand if you do not want to make this move.

**Comment by casperstorm** [comment]
I've been going through this, @tarkah and it is the way forward.
This is much more maintainable, faster compile time, and easier to test.

The plan will be the following:
I'll finish #129 and merge it to master. Then we will do some proper testing on master and make a release.
Meanwhile, this branch is finished, and master is back merged into it so we are ready to merge this and going forward using this structure. This is a huge improvement, and yes it is a big structural change but a needed one with the amount of features we keep doing. Good job mate and keep working on this.

**Comment by casperstorm** [comment]
@tarkah I'll finish my branch today or tomorrow. :)

**Comment by tarkah** [comment]
Great, glad you are aligned on this change! Sounds like a plan. Can't wait to see the release channels get finished up, that'll be a good addition. It's going to be a big release!

**Comment by tarkah** [comment]
I've rebased to master, this should be good to merge!

**Comment by tarkah** [comment]
I added a couple more `bins`... `parse_toc` and `fingerprint_addon`

**Pull request merged**
