### PR TITLE
feat: abstracted all categories option for a cleaner interface

### PR DESCRIPTION
**Pull request by kasperkronborg**
## Proposed Changes
  - Abstracts away the very implicit api of injecting the All Categories into the category dropdown.
  - The new interface implements both `Default` and a static function for retrieving the `all_option()` and it resembles the interface of the result size dropdown to generate a more cohesive codebase.

### CODE REVIEW

**Review by casperstorm — APPROVED** [review]
Normally I don't think its necessary to replace a string with a struct if it does not have a purpose for being a struct However I think it can be justified in this PR because the end product here is more readable than before.

**Comment by kasperkronborg** [comment]
@casperstorm optimized it ever further, so I no longer transforms the category string directly on the catalog struct, but's now all handled in the ui part of the application.

**Comment by casperstorm** [comment]
> @casperstorm optimized it ever further, so I no longer transforms the category string directly on the catalog struct, but's now all handled in the ui part of the application.

Nice, this is better. 👍🏻

**Comment by tarkah** [comment]
👌 nice!! This is perfect. We need to get ResultSize working directly in the picklist as well instead of the String of it. That's so much cleaner!

**Review by tarkah — APPROVED** [review]
Looks great! Love the change to enum, this feels a lot better.

**Pull request merged**
